### ISSUE TITLE
Have you thought about additional song books?

### ISSUE THREAD

**Issue by mudnug** [mrmcgibby/ldshymnlyrics#1]
Eventually a new hymnal will be released. Have you thought about whether you would want to host the text in it? Also, some musical numbers from the Children's Songbook would be useful. Would you prefer those be hosted in a different repository?

**Comment by mrmcgibby** [comment]
That's a good idea. I'll see what I can do. When a new hymnal is released, I'll likely need to update this.

**Comment by mrmcgibby** [comment]
Added the Children's Songbook. I haven't tested it so please file further issues with any problems.
